### ISSUE TITLE
2018 Version

### ISSUE THREAD

**Issue by rzimin** [steptosky/3DsMax-XplnObj#1]
Would be there an updated version for 2018?

**Comment by Pancir** [comment]
Hello sorry for delay, It seems my notifications setup is not correct.

Unfortunately 2018 version breaks backward compatibility for some part of the plugin, so it is not easy as it was before to make the plugin compatible with this version, I don't know how much time it will take but I work on it.

**Comment by rzimin** [comment]
Anyway,  good to hear and looking forward!

**Comment by rzimin** [comment]
Gents, 

any news for 2018 version?

**Comment by Pancir** [comment]
Hi, we haven't planned work on it yet, so there are no any news.
I hope it will be planned in next year.

**Comment by muchimi** [comment]
Thanks Pancir - it's becoming more and more of an issue as all the tools I use are for 2018 and using multiple versions of Max is getting to be complicated!

Appreciate all your efforts!

Cheers,

**Comment by OzWookiee** [comment]
Hey guys, just starting to get into this and only have Max2018 and am getting Error code 127 - The specified procedure could not be found.

**Comment by Pancir** [comment]
versions 2018+ aren't supported yet.

**Comment by OzWookiee** [comment]
Let us know when they are. Back to blender for me then =(

**Comment by Pancir** [comment]
This task will be closed and you will get an e-mail.

**Comment by Pancir** [comment]
Since the plug-in version `2.4.0-beta` you can use it with 3Ds Max 2018/2019.
[get plug-in](https://github.com/steptosky/3DsMax-XplnObj/releases)
