### ISSUE TITLE
X-LOD scale issue

### ISSUE THREAD

**Issue by muchimi** [steptosky/3DsMax-XplnObj#10]
Hi Pancir,

just found out that the export for the LOD (ATTR_LOD) has an interesting scaling question - not so much an issue. 

The LOD attribute fields are in meters but the value is scaled (inversely to the value of the parent object) - which is fine but very confusing.

Example, when using system units of millimeters, units set to meters, and a scale of 0.001 in X-OBJ:
A 50 in the near or far boxes for X-LOD (which 3DS displays in meters so it reads 50.0m) ends up putting a value of 50000 in the output OBJ file (50km).   I was expecting that to stay at 50.

Not a problem as the inputs can be scaled appropriately in the X-LOD input but food for thought if there's a way to have the LOD distance not scale (so in our example, 50 meters entered in 3DS stays 50m in the output file).

Cheers,

EM

**Comment by Pancir** [comment]
I will check it as soon as I can

**Comment by Pancir** [comment]
Should be fixed since version `2.4.0`
