### ISSUE TITLE
Aircraft Boeing 767-300ER

### ISSUE THREAD

**Issue by DemonRem** [steptosky/3DsMax-XplnObj#11]
does this aircraft used this plugin as export?

https://steptosky.com/index.php/aircrafts/12-boeing-767-300

**Comment by Pancir** [comment]
No, we don't use this plugin for our aircraft for historical reasons.

**Comment by DemonRem** [comment]
if may i ask which plugin then?

**Comment by Pancir** [comment]
Don't exactly know but the aircraft was exported with the blender.

**Comment by DemonRem** [comment]
i think i know what you speak, there is only 1 script probably in blender guess this is the one thet been used

https://github.com/der-On/XPlane2Blender
