### ISSUE TITLE
2018... 2019... Version

### ISSUE THREAD

**Issue by Choopa76** [steptosky/3DsMax-XplnObj#14]
Hi,
thanks first for the previous plug-ins to 3ds Max versions until 2017.
After unfortunately the version 2018 has been omitted, I wonder if there is still a plug-in for the new version of 3ds Max 2019? Or does the development end with the 2017 version?
3ds Max 2017 was one of the most useless versions ever. But, people love your exporter and would certainly be happy about the development. Although it might not be freeware.
Thank you for all the previous work. 😃 
B.R.

**Comment by Pancir** [comment]
#1 2018 Version

That issue describes why it is not so easy to support 2018 and higher version. 
We haven't planned to stop developing this plugin but unfortunately we still have other things with higher priority.

**Comment by muchimi** [comment]
Yep, with 2019 now here, getting support from Autodesk and plugin updates on older versions is getting to be a challenge.  The main point for me is 2017 (and any prior) has a lot of issues with DPI scaling, and the rest of my pipeline has already moved on (not my decision) to newer versions of software - makes it a challenge to work on something now more than 2 years old.    Thanks for the hard work @Pancir - appreciate any attention to this.  I'd really like to avoid adding Blender to my workflow :)
