### ISSUE TITLE
help

### ISSUE THREAD

**Issue by zhanglei1004** [steptosky/3DsMax-XplnObj#15]
I do not understand the process，Could you send me an example for 3Dmax to x-plane obj，thank you

**Comment by Pancir** [comment]
Unfortunately I don't have example projects.
Have you read the help? https://github.com/steptosky/3DsMax-XplnObj-Doc/releases

**Comment by zhanglei1004** [comment]
I read the help document，but I still can not know how to use the plugin，can you help me,thank you

**Comment by zhanglei1004** [comment]
@Pancir I read the help document，but I still can not know how to use the plugin，can you help me,thank you

**Comment by Pancir** [comment]
Could you describe the problem you have faced?

**Comment by zhanglei1004** [comment]
I have an aircraft 3d model which is designed by Catia，then I use 3Dmax open the model,and I can find the x-obj and X-lod,but I don't know other steps。

**Comment by zhanglei1004** [comment]
can you give me your email,I can send the picture to you,thank you

**Comment by Pancir** [comment]
You have to link the objects that you want to export to the x-obj in your scene then try to export. I recommend to learn the plug in with simple objects like boxes and teapots. Also be sure you use the right system units that  should be 'meters'.

**Comment by zhanglei1004** [comment]
![picture1](https://user-images.githubusercontent.com/41115532/42669661-399df8c2-8689-11e8-9c27-7dacd8a89ad2.PNG)
I link the objects with the x-obj，then，I export the obj，but I don't Know if this is  right？

**Comment by Pancir** [comment]
Yes, this should be right. But for final model it is not enough. You have to learn how to adjust your model correctly. The plug-in implements the [X-Plane obj specification](http://developer.x-plane.com/?article=obj8-file-format-specification) that each developer should know for creating good models.

**Comment by zhanglei1004** [comment]
![picture](https://user-images.githubusercontent.com/41115532/42670346-cbeddde8-868c-11e8-9b36-22ea8b5fa1a0.PNG)
when I use AC3D exported the x-plane model，the AC3D prompt a error

**Comment by Pancir** [comment]
We don't support AC3D you can use the [x-pane.org](https://forums.x-plane.org/index.php?/forums/) forum for getting help.

**Comment by zhanglei1004** [comment]
you usually how to convert the x-plane.obj to the format which x-plane maker can use，thank you，

**Comment by Pancir** [comment]
There are this plugin for 3DS max, plugin for Blender and plugin for AC3D. Use what you wish,

**Comment by zhanglei1004** [comment]
I append two plugins for AC3D，but still have this error，the plugins are XPlaneSupport.tcl and XPlaneSupportWin.p

**Comment by Pancir** [comment]
Sorry I can't help you with the AC3D.

**Comment by zhanglei1004** [comment]
oh，thank you very much，you usually how to convert the x-plane.obj to the format which x-plane maker can use

**Comment by Pancir** [comment]
We usually use the plugin for blender but by historical reasons only.

**Comment by zhanglei1004** [comment]
can you share the plugin for blender to me?thank you.

**Comment by Pancir** [comment]
I don't have it on my PC and I have never used it. That plugin is used by our 3d designers. You can use Google for searching that plugin.

**Comment by zhanglei1004** [comment]
I have download the blender,but I can not find the plugin which is used to read the xplane obj

**Comment by Pancir** [comment]
Please, use search engines like Google or forums like I have already specified before to solve your problems.
