### ISSUE TITLE
Textures doesn't show

### ISSUE THREAD

**Issue by Tapsiful** [steptosky/3DsMax-XplnObj#16]
Hi there,

Cannot get the textures to show after export from max with the plugin, neither in the plane maker nor in the simulator. Is there any info on how to appy textures in max with this plugin exactly?

What I tried without success:
- set the texture files (DDS) within max on the plugin's roll interface then export
- all the above + applying a material with the same texture set as diffuse bitmap then export

Do we have to name the material that we apply with a specific name? Do we have to apply material in max at all or setting in the plugin is enough? Any specific mandatory file structure in the max scene's folder?

**Comment by Pancir** [comment]
Hello, X-Obj just takes name of specified texture and prints it to .obj file, so your texture must be near your .obj file when x-plane loads that .obj. See this for more information [Attribute TEXTURE](https://developer.x-plane.com/?article=obj8-file-format-specification#TEXTURE_lttex_file_namegt)
Materials of 3Ds Max don't have any affects, so you can use any material on your objects.
