### ISSUE TITLE
Objects floating in the scen

### ISSUE THREAD

**Issue by mroc2019** [steptosky/3DsMax-XplnObj#19]
Hi,
I have an issue.
Evey objet I export from 3dsmax, displays in the Xplane floating above the terrain, tarmac or runway.  I have verified that the object is set to Z=0, I have tried exporting planes set to 0, and even so, they appear floating.  Any ideas?
What am I doing wrong?

**Comment by Pancir** [comment]
Hello, could you show a screenshot of the problem?

**Comment by mroc2019** [comment]
Thank you, already solved.  It turned out that the terrain is not flat, although it seems like it, so the plug in is working fine.
Cheers

**Comment by Pancir** [comment]
Glad to read that you have solved the problem.
