### ISSUE TITLE
Draw order - translucency

### ISSUE THREAD

**Issue by muchimi** [steptosky/3DsMax-XplnObj#21]
Pancir, question on the best way to setup draw order.
For translucency, x-plane requires surfaces behind a transparent / translucent object to be drawn first.  What is the best way to setup faces so I can specify which ones get exported "First" so they are drawn before the translucent ones?
I'm playing around with elements but not knowing which order things happen, I assume I need to re-order vertices/faces as x-plane probably draws in the order it sees them in the .OBJ.

Thanks!

M

**Comment by muchimi** [comment]
Actually - just figured out detach / attach works to re-order.  The faces attached last are drawn after the faces of the object doing the attaching....

**Comment by Pancir** [comment]
You also can detach necessary faces to another object and order it according to parent/children linkage:  https://3dsmax-xplnobj.readthedocs.io/en/master/start.html#scene-conception
And thank for information about your solution it seems good too.

**Comment by muchimi** [comment]
Thank you - I didn't think of doing it that way. 

I have a question then on how you handle texturing of an object hierarchy like this given the one texture rule per OBJ:  Not sure Max has a good way of UV mapping hierarchies onto a single material.  Running into that is one of the reasons I was using a single object to start with and just attaching things together.  

Having a single object helps me with relative shell scaling (texel density) and positioning - and of course - painting.  I'm still learning but so far trying to combine multiple UV maps and merging paints on a single texture has been hard labor - making large rocks into smaller rocks and as much fun as a root canal.

If only max had a magic button that says "reorder vertices" from a particular point - I think there is a new API that started in Max 18 to help with that - haven't looked into it.

I am also thinking in your script - consider using the materials ID to control the export order so that triangles with material 1 would appear in the OBJ before faces with material 2, etc...  Not sure how feasible that is but it would be a very nice to have!

**Comment by Pancir** [comment]
Since some 3d max version it is possible to add unwrap to more than one selected objects and editing their UV at the same time, perhaps it will help you.
About triangles ordering - I will think what I can do with this situation.
