### ISSUE TITLE
2-sided export does not work

### ISSUE THREAD

**Issue by RomSunZ** [steptosky/3DsMax-XplnObj#3]
2-sided option does not work at all. In exported obj attribute "ATTR_no_cull" does not appear at all.

**Comment by Pancir** [comment]
The situation around "Two sided" is described in the [help](https://github.com/steptosky/3DsMax-XplnObj-Doc/releases).

> Two sided – It replaces ATTR_no_cull which is deprecated. If it is checked the exporter will make the geometry copy at the same place and reverse its normals while exporting, it does not affect the 3Ds Max’s scene.

**Comment by Pancir** [comment]
https://github.com/steptosky/XplnObj/commit/23007c836b7a866857701a20d13f7025640cbb2e
The fix will be available in the next release
