### ISSUE TITLE
Custom light name does not export

### ISSUE THREAD

**Issue by RomSunZ** [steptosky/3DsMax-XplnObj#4]
If "Light type" is set to "Param" and "Light Param" is set to "Custom" instead of "Custom name" to obj file export "LIGHT_PARAM light_params_custom".

**Comment by Pancir** [comment]
Thank you, I will fix it next version.

**Comment by Pancir** [comment]
It has been fixed.

https://github.com/steptosky/XplnObj/commit/8408ea61b6486ebf9d91975985df4ff401f6a96d
https://github.com/steptosky/3DsMax-XplnObj/commit/a25e555066b12945a1e8a7d9a8d210324afa4bb9
