### ISSUE TITLE
Mirrored shapes export bug

### ISSUE THREAD

**Issue by RomSunZ** [steptosky/3DsMax-XplnObj#5]
Mirrored shapes with option "Transform" exported with flipped normals. Mirrored with modifier "Mirror" exported OK.
See attachment.
![mirrored bug](https://user-images.githubusercontent.com/10460695/30002934-e544ea64-90df-11e7-9405-8ec4564c49c9.jpg)

**Comment by Pancir** [comment]
Mirrored transforms are not supported yet.

**Comment by Pancir** [comment]
Added https://github.com/steptosky/XplnObj/commit/0f1dadb89c844ddcbeaf72232440a2420ccc4306
