### ISSUE TITLE
Param Light custom name field and export

### ISSUE THREAD

**Issue by muchimi** [steptosky/3DsMax-XplnObj#8]
Having a minor issues exporting a PARAM type light with a custom name (so, using a light that is not in the default pick list for param type lights):

**Steps to reproduce:** 2.2.1 release:
1) add a spot (or omni) light to the model
2) change x-plane attribute to "Param light"
3) change x-plane param light type to "Custom"
4) Observe: custom name field is still disabled - a custom name cannot be entered - such as - "sodium_flood_XYZBTSS".  Expected behavior: the custom name field is active so a custom name can be entered.
5) deselect the light object in the model, and then reselect it (forces a rollup update)
6) Observe: custom name field is now enabled and a custom name can be entered
7) set custom name and additional parameters as needed
8) export model
9) Observe: export light name says "light_params_custom" in the OBJ output file instead of the custom name entered in the custom field.   Expected behavior: the custom light name is exported.

This happens in Max 2015, 2016 and 2017.  I should note I have the rollup docked on the UI so not sure if that has anything to do with the custom name box getting enabled for input.

I also installed the 2.2.0 release to check and observed the same behavior.

Perhaps I missed something in how it's supposed to work and should go read the manual again :)

Cheers,

M

**Comment by Pancir** [comment]
Thank you for your detailed report, this problem has already been fixed and will be available in the next release.
Issue https://github.com/steptosky/3DsMax-XplnObj/issues/4
