### ISSUE TITLE
LODs ordering problem

### ISSUE THREAD

**Issue by RomSunZ** [steptosky/3DsMax-XplnObj#9]
Please adjust export sequence according to object's name in 3ds. Now export sequence corresponds to first created->first exported. It is inroper for example if you export LODs.
P.S. Where can I download dlu with light names fix? Can you mail it?

**Comment by Pancir** [comment]
Do I understand correctly you are talking about the export window's "Objects for exporting" section, and you want the object list to be sorted by object name?
Anyway, LODs will be sorted by their distance during export. Also, objects order depends on their hierarchy, read "Scene Conception" section in the [help](https://github.com/steptosky/3DsMax-XplnObj-Doc/releases). 
So sorting will affect X-Obj order in the export window's "Objects for exporting" section only. Is this what you want?

About new version I have planed to release it within a week.

**Comment by RomSunZ** [comment]
1. No, not objects on export window, I mean parts inside particular object. Lights for example exported same way first created->first exported.
2. If LODs are sorted by plugin so there is error. If I use additive LODs in model this sort doesn't work correctly.
For example I have 3 LODs (in sequence it MUST be exported):
ATTR_LOD 0.00000 1500.00000 
ATTR_LOD 1500.00000 11000.00000 
ATTR_LOD 0.00000 11000.00000 

But exporter sort them this way:
ATTR_LOD 0.00000 1500.00000
ATTR_LOD 0.00000 11000.00000 
ATTR_LOD 1500.00000 11000.00000 

It is incorrect as in this case Xplane throws error: The object bla-bla-bla  has an LOD starting at 1500.000000 that does not match the previous LOD.

That's why I asked about ability to manually sort LODs.

By the way, thank you very much for this plugin. I tried Blender and sketchup as suggested by X plane developers, but these programs are very ugly compared to 3ds.

**Comment by Pancir** [comment]
Thank you, I will check this situation.

> By the way, thank you very much for this plugin. I tried Blender and sketchup as suggested by X plane developers, but these programs are very ugly compared to 3ds.

You are welcome! Today, 3Ds Max has more well tools than other programs.

**Comment by zhenglei1004** [comment]
I do not understand the process，Could you send me an example for 3Dmax to x-plane obj，thank you

**Comment by Pancir** [comment]
Should be fixed since version `2.5.0`
